#!/usr/bin/env python3
"""Generate user/go/webrender/font/font8x8.go from user/src/lib/font8x8.zig.

The VirelaiOS 8x8 bitmap font (public domain - Daniel Hepper's font8x8_basic.h,
based on Marcel Sondaar / IBM public-domain VGA fonts) is this project's own
text asset. The Go browser renderer reuses that same table instead of importing
a font library, so the guest and the Zig userland draw identical glyphs.

Convention (copied from the Zig source): each glyph is 8 rows of one byte,
bit 0 (LSB) is the leftmost pixel, a set bit is foreground. Index = ASCII - 0x20.

Usage (from the repository root):
    python3 tools/go/extract-font8x8.py
"""

from __future__ import annotations

import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
ZIG = REPO / "user" / "src" / "lib" / "font8x8.zig"
OUT = REPO / "user" / "go" / "webrender" / "font" / "font8x8.go"

GLYPH_RE = re.compile(r"\.\{\s*((?:0x[0-9a-fA-F]{2}\s*,\s*){7}0x[0-9a-fA-F]{2})\s*\}")
BYTE_RE = re.compile(r"0x([0-9a-fA-F]{2})")


def main() -> int:
    if not ZIG.is_file():
        print(f"extract-font8x8: missing {ZIG}", file=sys.stderr)
        return 1
    text = ZIG.read_text()

    glyphs = []
    for match in GLYPH_RE.finditer(text):
        rows = [int(b, 16) for b in BYTE_RE.findall(match.group(1))]
        if len(rows) == 8:
            glyphs.append(rows)

    if len(glyphs) != 95:
        print(f"extract-font8x8: expected 95 glyphs, parsed {len(glyphs)}", file=sys.stderr)
        return 1

    lines = [
        "// Code generated by tools/go/extract-font8x8.py; DO NOT EDIT.",
        "//",
        "// Source: user/src/lib/font8x8.zig (the VirelaiOS 8x8 bitmap font,",
        "// public domain: Daniel Hepper's font8x8_basic.h, based on",
        "// Marcel Sondaar / IBM public-domain VGA fonts).",
        "//",
        "// One glyph = 8 rows of one byte; bit 0 is the leftmost pixel; a set",
        "// bit is foreground. Index = ASCII - 0x20, 95 printable glyphs.",
        "package font",
        "",
        "// Font8x8 is the 95 printable ASCII glyphs (0x20-0x7e), 8x8 each.",
        "var Font8x8 = [95][8]byte{",
    ]
    for i, rows in enumerate(glyphs):
        ch = chr(0x20 + i)
        if ch == "\\":
            label = "'\\\\'"
        elif ch == "'":
            label = "\"'\""
        else:
            label = f"'{ch}'"
        body = ", ".join(f"0x{b:02x}" for b in rows)
        lines.append(f"\t{{{body}}}, // {label}")
    lines.append("}")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"extract-font8x8: wrote {OUT.relative_to(REPO)} ({len(glyphs)} glyphs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
