"""Configuration loading and defaults.

``ragshit init`` writes ``.ragshit.toml`` and ``.ragshitignore`` at the
repository root. All retrieval behavior is driven by these values; the
defaults are the canonical numbers documented in ``docs/ranking.md``.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

try:  # Python >= 3.11
    import tomllib
except ImportError:  # pragma: no cover - Python 3.9/3.10
    from . import _toml as tomllib

from .errors import ConfigError

CONFIG_FILENAME = ".ragshit.toml"
IGNORE_FILENAME = ".ragshitignore"

DEFAULT_INDEX = {
    "database": ".ragshit/index.sqlite3",
    "include_untracked": False,
    "max_file_bytes": 1048576,
    "follow_symlinks": False,
}

DEFAULT_RETRIEVAL = {
    "default_limit": 20,
    "maximum_limit": 100,
    "changed_file_boost": 2.0,
    "path_match_boost": 4.0,
    "symbol_match_boost": 5.0,
    "heading_match_boost": 3.0,
    "heading_token_boost": 1.0,
    "symbol_token_boost": 1.0,
    "coverage_boost": 1.0,
    "changed_line_boost": 2.0,
    "recent_change_boost": 0.5,
    "decision_doc_boost": 0.5,
    "fts_weight": 8.0,
    "phrase_boost": 2.0,
}

DEFAULT_BUNDLE = {
    "maximum_characters": 120000,
    "include_git_status": True,
    "include_recent_commits": True,
    "recent_commit_count": 10,
    "include_diff": True,
}

DEFAULT_EMBEDDINGS = {
    "enabled": False,
    "provider": "disabled",
}

CONFIG_TEMPLATE = """\
# Ragshit configuration for this repository.
# Generated by `ragshit init`. All keys are optional; absent keys use the
# defaults below. See docs/configuration.md for details.

[index]
database = ".ragshit/index.sqlite3"
include_untracked = false
max_file_bytes = 1048576
follow_symlinks = false

[retrieval]
default_limit = 20
maximum_limit = 100
changed_file_boost = 2.0
path_match_boost = 4.0
symbol_match_boost = 5.0
heading_match_boost = 3.0

[bundle]
maximum_characters = 120000
include_git_status = true
include_recent_commits = true
recent_commit_count = 10
include_diff = true

[embeddings]
enabled = false
provider = "disabled"
"""

DEFAULT_RAGSHITIGNORE = """\
# Ragshit ignores. Patterns are gitignore-style.
# Tracked files stay eligible even when .gitignore matches them, unless
# they are listed here explicitly.

.git/
.ragshit/
.zig-cache/
zig-out/
node_modules/
__pycache__/
*.img
*.bin
*.efi
*.elf
*.o
*.a
*.dylib
*.so
artifacts/efi-vars.bin
"""

_INT_KEYS = {"max_file_bytes", "maximum_limit", "recent_commit_count", "default_limit"}
_FLOAT_KEYS = {
    "changed_file_boost",
    "path_match_boost",
    "symbol_match_boost",
    "heading_match_boost",
    "heading_token_boost",
    "symbol_token_boost",
    "changed_line_boost",
    "recent_change_boost",
    "decision_doc_boost",
    "fts_weight",
    "phrase_boost",
    "maximum_characters",
}
_BOOL_KEYS = {"include_untracked", "follow_symlinks", "include_git_status",
              "include_recent_commits", "include_diff", "enabled"}
_STR_KEYS = {"database", "provider"}


def _coerce(section: str, data: Dict[str, Any], defaults: Dict[str, Any]) -> Dict[str, Any]:
    result = dict(defaults)
    for key, value in data.items():
        if key not in defaults:
            raise ConfigError(f"unknown key '{key}' in [{section}] (supported: {', '.join(sorted(defaults))})")
        if isinstance(value, bool):
            ok = key in _BOOL_KEYS
            expected = "boolean"
        elif isinstance(value, int):
            ok = key in _INT_KEYS or key in _FLOAT_KEYS
            expected = "number"
        elif isinstance(value, float):
            ok = key in _FLOAT_KEYS
            expected = "number"
        elif isinstance(value, str):
            ok = key in _STR_KEYS
            expected = "string"
        else:
            ok = False
            expected = "scalar"
        if not ok:
            raise ConfigError(f"[{section}] {key} must be a {expected}, got {type(value).__name__}")
        result[key] = value
    return result


@dataclass
class IndexConfig:
    database: str = ".ragshit/index.sqlite3"
    include_untracked: bool = False
    max_file_bytes: int = 1048576
    follow_symlinks: bool = False

    @classmethod
    def from_mapping(cls, data: Dict[str, Any]) -> "IndexConfig":
        return cls(**_coerce("index", data, DEFAULT_INDEX))


@dataclass
class RetrievalConfig:
    default_limit: int = 20
    maximum_limit: int = 100
    changed_file_boost: float = 2.0
    path_match_boost: float = 4.0
    symbol_match_boost: float = 5.0
    heading_match_boost: float = 3.0
    heading_token_boost: float = 1.0
    symbol_token_boost: float = 1.0
    coverage_boost: float = 1.0
    changed_line_boost: float = 2.0
    recent_change_boost: float = 0.5
    decision_doc_boost: float = 0.5
    fts_weight: float = 8.0
    phrase_boost: float = 2.0

    @classmethod
    def from_mapping(cls, data: Dict[str, Any]) -> "RetrievalConfig":
        return cls(**_coerce("retrieval", data, DEFAULT_RETRIEVAL))


@dataclass
class BundleConfig:
    maximum_characters: int = 120000
    include_git_status: bool = True
    include_recent_commits: bool = True
    recent_commit_count: int = 10
    include_diff: bool = True

    @classmethod
    def from_mapping(cls, data: Dict[str, Any]) -> "BundleConfig":
        return cls(**_coerce("bundle", data, DEFAULT_BUNDLE))


@dataclass
class EmbeddingsConfig:
    enabled: bool = False
    provider: str = "disabled"

    @classmethod
    def from_mapping(cls, data: Dict[str, Any]) -> "EmbeddingsConfig":
        return cls(**_coerce("embeddings", data, DEFAULT_EMBEDDINGS))


@dataclass
class RagshitConfig:
    index: IndexConfig = field(default_factory=IndexConfig)
    retrieval: RetrievalConfig = field(default_factory=RetrievalConfig)
    bundle: BundleConfig = field(default_factory=BundleConfig)
    embeddings: EmbeddingsConfig = field(default_factory=EmbeddingsConfig)

    @classmethod
    def from_file(cls, root: Path) -> "RagshitConfig":
        path = root / CONFIG_FILENAME
        if not path.exists():
            return cls()
        try:
            raw = path.read_bytes()
        except OSError as exc:
            raise ConfigError(f"cannot read {path}: {exc}") from exc
        try:
            data = tomllib.loads(raw.decode("utf-8"))
        except Exception as exc:  # tomllib.TOMLDecodeError or our ValueError
            raise ConfigError(f"invalid TOML in {path}: {exc}") from exc
        known = {"index", "retrieval", "bundle", "embeddings"}
        for section in data:
            if section not in known:
                raise ConfigError(f"unknown section [{section}] in {path}")
        return cls(
            index=IndexConfig.from_mapping(data.get("index", {})),
            retrieval=RetrievalConfig.from_mapping(data.get("retrieval", {})),
            bundle=BundleConfig.from_mapping(data.get("bundle", {})),
            embeddings=EmbeddingsConfig.from_mapping(data.get("embeddings", {})),
        )


def config_path(root: Path) -> Path:
    return root / CONFIG_FILENAME


def write_default_config(root: Path) -> None:
    """Write .ragshit.toml and .ragshitignore if they do not exist."""
    cfg = root / CONFIG_FILENAME
    if not cfg.exists():
        cfg.write_text(CONFIG_TEMPLATE, encoding="utf-8")
    ign = root / IGNORE_FILENAME
    if not ign.exists():
        ign.write_text(DEFAULT_RAGSHITIGNORE, encoding="utf-8")


def resolve_database_path(root: Path, config: RagshitConfig) -> Path:
    db = config.index.database
    if os.path.isabs(db):
        return Path(db)
    return (root / db).resolve()
