#!/usr/bin/env bash
#
# inventory-gates.sh -- regenerate (or --check) the machine-generated gate
# fleet inventory (M40 GF1, issue #934).
#
# Every executable script directly under tools/ gets one row: line count,
# class (A/B/C/D/tooling -- explicit exceptions below, prefix defaults
# otherwise), registration status (just recipe? gate-inventory row?
# CI-sharded via the archive GATE block? status.md row?), and a one-line
# purpose scraped from its own header comment. A gate-class script
# registered nowhere is listed as an ORPHAN.
#
# Usage:
#   bash tools/inventory-gates.sh          # rewrite docs/gate-fleet-inventory.md
#   bash tools/inventory-gates.sh --check  # fail (rc=1) if the tracked file
#                                          # differs from a fresh render --
#                                          # this is the registration guard:
#                                          # a new script changes the render,
#                                          # so it fails until the report is
#                                          # regenerated and committed.
#   just inventory-gates [--check]
#
# Deterministic by construction: LC_ALL=C sorting, no dates, no revisions,
# no host state. A fresh render on a clean tree is byte-identical.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

REPORT="docs/gate-fleet-inventory.md"
CHECK=0
[ "${1:-}" = "--check" ] || true
if [ "${1:-}" = "--check" ]; then CHECK=1; fi

class_of() {
    case "$1" in
        # Class C (interactive) -- gate-inventory.md non-gate registers.
        verify-pointer-manual.sh) echo "C"; return ;;
        # Class D (diagnostics, not gates).
        verify-preexit-tx.sh|verify-tx-diag.sh|verify-tx-transition.sh|\
        verify-fw-mmu-capture.sh|verify-t0sz16-walkprobe.sh|verify-t0sz16.sh|\
        audit-vz-irq-api.sh|probe-pointer-routes.sh|test-unicode-torture.sh) echo "D"; return ;;
        # Class B without the verify-live- prefix.
        verify-bad-handoff.sh|verify-marker.sh|verify-nvram-console.sh|\
        verify-host-console.sh|verify-custom-virtio.sh|verify-cvc-echo.sh|\
        verify-zc-corpus.sh) echo "B"; return ;;
        # Class A without the live prefix (portable / CI).
        verify-transcript.sh|verify-unit-tests.sh|verify-mmu-debt.sh|\
        verify-bss-budget.sh|verify-mutations.sh|verify-glyph-raster.sh|\
        verify-ttf-fonts.sh|verify-vf-class-a.sh|check-zc-host-contract.py) echo "A"; return ;;
        verify-live-*.sh) echo "B"; return ;;
        verify-*.sh) echo "A"; return ;;
        *) echo "tooling"; return ;;
    esac
}

# First "# text" header line (or """docstring opener for .py) in the
# first 12 lines; truncated, pipe-escaped for the markdown table.
purpose_of() {
    awk 'NR<=12 {
        if ($0 ~ /^# [^ ]/) { sub(/^# /, ""); print; exit }
        if ($0 ~ /^"""/) { sub(/^"""/, ""); print; exit }
    }' "$1" | cut -c1-110 | sed 's/|/\\|/g; s/[[:space:]]*$//'
}

has_just() {
    local name="${1%.sh}"
    name="${name%.py}"
    grep -q "^${name}:" justfile 2>/dev/null
}

render_to() {
    local out="$1"
    local total=0 live=0 orphans=0
    local orphan_list="" rows=""
    local nA=0 nB=0 nC=0 nD=0 nT=0 just_yes=0 inv_yes=0 ci_yes=0 st_yes=0

    while IFS= read -r f; do
        base="$(basename "$f")"
        lines="$(wc -l < "$f" | tr -d ' ')"
        cls="$(class_of "$base")"
        total=$((total + 1))
        case "$cls" in
            A) nA=$((nA+1)) ;; B) nB=$((nB+1)) ;; C) nC=$((nC+1)) ;;
            D) nD=$((nD+1)) ;; *) nT=$((nT+1)) ;;
        esac
        case "$cls" in
            B) if [ "${base%.sh}" != "${base}" ] && [ "${base#verify-live-}" != "$base" ]; then live=$((live+1)); fi ;;
        esac
        if has_just "$base"; then j="y"; just_yes=$((just_yes+1)); else j="n"; fi
        if grep -qF "$base" docs/gate-inventory.md docs/archive/gate-inventory-detail.md 2>/dev/null; then
            v="y"; inv_yes=$((inv_yes+1)); else v="n"; fi
        if grep -qF "tools/$base" docs/archive/gate-inventory-detail.md 2>/dev/null; then
            c="y"; ci_yes=$((ci_yes+1)); else c="n"; fi
        if grep -qF "$base" docs/status.md 2>/dev/null; then
            s="y"; st_yes=$((st_yes+1)); else s="n"; fi
        pur="$(purpose_of "$f")"
        [ -n "$pur" ] || pur="(no header line)"
        if { [ "$cls" = "A" ] || [ "$cls" = "B" ] || [ "$cls" = "C" ] || [ "$cls" = "D" ]; } \
            && [ "$j" = "n" ] && [ "$v" = "n" ] && [ "$s" = "n" ]; then
            orphans=$((orphans+1))
            orphan_list="${orphan_list}${base}"$'\n'
        fi
        rows="${rows}| \`$base\` | $lines | $cls | $j | $v | $c | $s | $pur |"$'\n'
    done <<EOF
$(LC_ALL=C ls tools/*.sh tools/*.py 2>/dev/null | LC_ALL=C sort)
EOF

    {
        echo "# Gate fleet inventory (generated)"
        echo
        echo "> Machine-generated by \`bash tools/inventory-gates.sh\` (M40 GF1,"
        echo "> issue #934). **Do not hand-edit** -- re-render instead. The"
        echo "> \`--check\` mode fails when the tracked file drifts from a fresh"
        echo "> render, so every new script under \`tools/\` must arrive with a"
        echo "> regenerated report. Subdirectory tooling (\`lib/\`, \`status/\`,"
        echo "> \`context/\`, \`gate/\`, \`ragshit/\`) is summarized below, not rowed."
        echo
        echo "## Summary"
        echo
        echo "| metric | count |"
        echo "|---|---|"
        echo "| top-level scripts (\`tools/*.sh\` + \`tools/*.py\`) | $total |"
        echo "| class A (portable / CI) | $nA |"
        echo "| class B (VZ hardware gate) | $nB (of which \`verify-live-*\`: $live) |"
        echo "| class C (interactive) | $nC |"
        echo "| class D (diagnostic) | $nD |"
        echo "| tooling (not gates) | $nT |"
        echo "| with a just recipe | $just_yes |"
        echo "| named in gate-inventory.md or the archive GATE block | $inv_yes |"
        echo "| CI-sharded (archive GATE block \`cmd=\`) | $ci_yes |"
        echo "| named in docs/status.md | $st_yes |"
        echo "| **orphans (gate-class, registered nowhere)** | **$orphans** |"
        echo
        echo "## Subdirectory tooling (not gates)"
        echo
        echo "| dir | files | role |"
        echo "|---|---|---|"
        for d in lib status context ragshit gate; do
            n="$(find "tools/$d" -type f 2>/dev/null | wc -l | tr -d ' ')"
            case "$d" in
                lib) r="per-run isolation for live gates (\`gate-run.sh\`)" ;;
                status) r="multiagent coordination gate + claim tooling (class A)" ;;
                context) r="context snapshot helpers" ;;
                gate) r="M40 vgate harness + specs (GF2+)" ;;
                ragshit) r="host-side context engine (developer tooling, not guest software)" ;;
            esac
            echo "| \`tools/$d/\` | $n | $r |"
        done
        echo
        echo "## Orphans"
        echo
        if [ "$orphans" -eq 0 ]; then
            echo "None -- every gate-class script is registered somewhere."
        else
            echo "Gate-class scripts with no just recipe, no inventory row, and no"
            echo "status.md row (migration order for GF3/GF4 is biggest-family first;"
            echo "this list only needs to shrink):"
            echo
            printf '%s' "$orphan_list" | sed 's/^/- `/' | sed 's/$/`/'
        fi
        echo
        echo "## All top-level scripts"
        echo
        echo "Columns: \`just\` = justfile recipe of the same name; \`inv\` = named in"
        echo "\`docs/gate-inventory.md\` or \`docs/archive/gate-inventory-detail.md\`;"
        echo "\`ci\` = \`cmd=\` in the archive GATE block (what vz-gates.yml shards);"
        echo "\`st\` = named in \`docs/status.md\` (\`y\` = yes, \`n\` = no throughout)."
        echo
        echo "| script | lines | class | just | inv | ci | st | purpose |"
        echo "|---|---|---|---|---|---|---|---|"
        printf '%s' "$rows"
    } > "$out"
}

if [ "$CHECK" -eq 1 ]; then
    tmp="$(mktemp -d "${TMPDIR:-/tmp}/inv-check.XXXXXX")/report.md"
    render_to "$tmp"
    if cmp -s "$tmp" "$REPORT"; then
        echo "inventory-gates --check: OK ($REPORT matches a fresh render)"
    else
        echo "inventory-gates --check: FAIL -- $REPORT drifted from a fresh render."
        echo "Run 'bash tools/inventory-gates.sh' (or 'just inventory-gates') and commit the result."
        diff -u "$REPORT" "$tmp" | head -30 || true
        exit 1
    fi
else
    render_to "$REPORT"
    echo "wrote $REPORT"
fi
