#!/usr/bin/env bash
#
# verify-live-elf.sh -- M22 D1 class-B gate (issue #324, claim 9815): the
# kernel's AArch64 ELF loader loads and executes a real ELF executable from
# the ESP on real VZ hardware.
#
# The chain, all asserted in vm-serial.log:
#   1. HELLO.ELF (generated by tools/mkhello-elf.py — a minimal statically
#      linked AArch64 ELF32 with one R+X PT_LOAD segment at 0x400000) is on
#      the ESP — the image builder embeds it, `ls` lists it.
#   2. `exec HELLO.ELF` sniffs the \x7fELF magic inside exec.exec_file,
#      parses + validates the image through kernel/src/elf.zig, stages the
#      segment at the EL0 text aperture, rebuilds the user root, and spawns
#      the EL0t task — the reply line "exec: loaded HELLO.ELF size=..."
#      proves the load (size = p_filesz/p_memsz).
#   3. The loaded program executes at EL0: its sys_write marker line
#      ("elf: hello from HELLO.ELF") lands in the serial log directly and
#      sys_exit closes the lifecycle with status 42 ("tasks user-exec
#      exited status=42" + reap).
#   4. The shell stays responsive (echo reply) and nothing parked in an
#      exception handler.
#
# The script is forwarded only AFTER the static claim-8215 payload has
# exited ("tasks user-el0 exited status=7").

# Run isolation (#523 item 2 / issue #528, claim 5069): every boot attaches
# a private DiskImageKit stacked disk (read-only base + throwaway ASIF
# overlay), a private EFI var store (recreated fresh per boot, as the
# pre-isolation gate did), and a private serial log under $RUN_DIR — two
# concurrent instances cannot clobber each other's disks, NVRAM, or
# evidence. Set VIRELAI_GATE_SUFFIX=_alt to give this instance its own
# canonical evidence names (two simultaneous instances MUST differ), and
# VIRELAI_KEEP_RUN=1 to keep the scratch dir.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

source tools/lib/gate-run.sh

SUFFIX="${VIRELAI_GATE_SUFFIX:-}"
art() { printf 'artifacts/%s%s' "$1" "$SUFFIX"; }

GATE_LOG="$(art m22-elf-live.txt)"
exec > >(tee "$GATE_LOG") 2>&1
trap 'gate_end 2>/dev/null || true; sleep 0.5' EXIT

BOOTS="${BOOTS:-1}"
REPORT="$(art live-elf-report.txt)"
STATIC_EXIT_LINE="tasks user-el0 exited status=7"
EXEC_EXIT_LINE="tasks user-exec exited status=42"
EXEC_REAP_LINE="tasks user-exec reaped"

echo "=== verify-live-elf: M22 D1 (issue #324) — load + execute an AArch64 ELF32 from the ESP at EL0, $BOOTS boot(s) ==="
zig version
swift --version 2>&1 | head -1
sw_vers
REVISION="$(git rev-parse HEAD 2>/dev/null || echo unknown)"
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
DIRTY="$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')"
echo "revision: $REVISION branch=$BRANCH boots=$BOOTS dirty-files=$DIRTY"

zig fmt --check boot/src/*.zig kernel/src/*.zig user/src/*.zig build.zig
zig build
zig build image
swift build --package-path host/vm-runner --configuration release -Xswiftc -DSPIKE
codesign --force --sign - --entitlements host/vm-runner/entitlements.plist host/vm-runner/.build/release/VMRunner

# --- per-run isolation -------------------------------------------------------------
# Private scratch dir + pristine-boot overlay for EVERY boot.
# See tools/lib/gate-run.sh.
gate_begin live-elf
gate_seed_share
echo "run dir: $RUN_DIR"
SCRIPT="$RUN_DIR/script.txt"


printf 'ls\nexec HELLO.ELF\necho rx-elf-ok\n' > "$SCRIPT"

run_one() {
    local tag="$1"
    local run_log="$(art live-elf-run-$tag.txt)"
    local serial_copy="$(art live-elf-serial-$tag.log)"
    rm -f "$RUN_DIR/efi-vars.bin" "$RUN_DIR/vm-serial-$tag.log"

    set +e
    host/vm-runner/.build/release/VMRunner "${GATE_RUNNER_ARGS[@]}" \
        --serial "$RUN_DIR/vm-serial-$tag.log" \
        --script "$SCRIPT" --script-after "$STATIC_EXIT_LINE" \
        --script-expect "$EXEC_REAP_LINE" --timeout 60 > "$run_log" 2>&1
    local rc=$?
    set -e
    [ -f "$RUN_DIR/vm-serial-$tag.log" ] && cp "$RUN_DIR/vm-serial-$tag.log" "$(art live-elf-serial-$tag.log)" || true
    local SER="$serial_copy"

    local bytes=0 banner=0 listed=0 loaded=0 hello=0 exited=0 reaped=0 echo_ok=0 fatal=0
    if [ -f "$SER" ]; then
        bytes="$(wc -c < "$SER" | tr -d ' ')"
        [ "$(grep -aFxc -- "VirelaiOS kernel has seized control." "$SER" || true)" = 1 ] && banner=1
        [ "$(grep -aFc -- "HELLO.ELF" "$SER" || true)" -ge 2 ] && listed=1
        [ "$(grep -aFc -- "exec: loaded HELLO.ELF size=" "$SER" || true)" = 1 ] && loaded=1
        [ "$(grep -aFxc -- "elf: hello from HELLO.ELF" "$SER" || true)" = 1 ] && hello=1
        [ "$(grep -aFxc -- "$EXEC_EXIT_LINE" "$SER" || true)" = 1 ] && exited=1
        [ "$(grep -aFxc -- "$EXEC_REAP_LINE" "$SER" || true)" = 1 ] && reaped=1
        [ "$(grep -aFxc -- "rx-elf-ok" "$SER" || true)" = 1 ] && echo_ok=1
        grep -qF -- "[EXC] parking:" "$SER" && fatal=1 || true
    fi
    echo "$tag: runner-rc=$rc serial-bytes=$bytes banner=$banner listed=$listed loaded=$loaded hello=$hello exited=$exited reaped=$reaped echo=$echo_ok fatal=$fatal" | tee -a "$REPORT"
    [ "$rc" = 0 ] && [ "$banner" = 1 ] && [ "$listed" = 1 ] && [ "$loaded" = 1 ] && \
        [ "$hello" = 1 ] && [ "$exited" = 1 ] && [ "$reaped" = 1 ] && \
        [ "$echo_ok" = 1 ] && [ "$fatal" = 0 ]
}

: > "$REPORT"
{
    echo "VIRELAIOS live ELF-loader gate (M22 D1, issue #324, claim 9815)"
    echo "revision: $REVISION branch=$BRANCH boots=$BOOTS dirty-files=$DIRTY"
    echo "script: $(cat "$SCRIPT" | tr '\n' '|')"
    echo "date: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo
} >> "$REPORT"

pass=0
n=0
while [ "$n" -lt "$BOOTS" ]; do
    n=$((n + 1))
    echo
    echo "=== live-elf boot $n ==="
    if run_one "$(printf '%02d' "$n")"; then pass=$((pass + 1)); fi
done

echo
echo "=== result ==="
if [ "$pass" = "$BOOTS" ]; then
    echo "verify-live-elf: PASS — HELLO.ELF parsed by kernel/src/elf.zig through the exec magic-sniff path, mapped at the EL0 text aperture, executed (sys_write marker), and exited cleanly ($pass/$BOOTS boot(s))."
    echo "PASS: $pass/$BOOTS" >> "$REPORT"
    exit 0
fi
echo "verify-live-elf: FAILED — $pass/$BOOTS boot(s) passed; see $REPORT and per-boot logs."
echo "FAIL: $pass/$BOOTS" >> "$REPORT"
exit 1
