#!/usr/bin/env bash
#
# verify-live-elf.sh -- M22 D1 class-B gate (issue #324, claim 9815): the
# kernel's AArch64 ELF loader loads and executes a real ELF executable from
# the ESP on real VZ hardware.
#
# The chain, all asserted in vm-serial.log:
#   1. HELLO.ELF (generated by tools/mkhello-elf.py — a minimal statically
#      linked AArch64 ELF32 with one R+X PT_LOAD segment at 0x400000) is on
#      the ESP — the image builder embeds it, `ls` lists it.
#   2. `exec HELLO.ELF` sniffs the \x7fELF magic inside exec.exec_file,
#      parses + validates the image through kernel/src/elf.zig, stages the
#      segment at the EL0 text aperture, rebuilds the user root, and spawns
#      the EL0t task — the reply line "exec: loaded HELLO.ELF size=..."
#      proves the load (size = p_filesz/p_memsz).
#   3. The loaded program executes at EL0: its sys_write marker line
#      ("elf: hello from HELLO.ELF") lands in the serial log directly and
#      sys_exit closes the lifecycle with status 42 ("tasks user-exec
#      exited status=42" + reap).
#   4. The shell stays responsive (echo reply) and nothing parked in an
#      exception handler.
#
# The script is forwarded only AFTER the static claim-8215 payload has
# exited ("tasks user-el0 exited status=7").

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

GATE_LOG="artifacts/m22-elf-live.txt"
exec > >(tee "$GATE_LOG") 2>&1
trap 'sleep 0.5' EXIT

BOOTS="${BOOTS:-1}"
REPORT="artifacts/live-elf-report.txt"
SCRIPT="artifacts/live-elf-script.txt"
STATIC_EXIT_LINE="tasks user-el0 exited status=7"
EXEC_EXIT_LINE="tasks user-exec exited status=42"
EXEC_REAP_LINE="tasks user-exec reaped"

echo "=== verify-live-elf: M22 D1 (issue #324) — load + execute an AArch64 ELF32 from the ESP at EL0, $BOOTS boot(s) ==="
zig version
swift --version 2>&1 | head -1
sw_vers
REVISION="$(git rev-parse HEAD 2>/dev/null || echo unknown)"
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
DIRTY="$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')"
echo "revision: $REVISION branch=$BRANCH boots=$BOOTS dirty-files=$DIRTY"

zig fmt --check boot/src/*.zig kernel/src/*.zig user/src/*.zig build.zig
zig build
zig build image
swift build --package-path host/vm-runner --configuration release
codesign --force --sign - --entitlements host/vm-runner/entitlements.plist host/vm-runner/.build/release/VMRunner

printf 'ls\nexec HELLO.ELF\necho rx-elf-ok\n' > "$SCRIPT"

run_one() {
    local tag="$1"
    local run_log="artifacts/live-elf-run-$tag.txt"
    local serial_copy="artifacts/live-elf-serial-$tag.log"
    rm -f artifacts/efi-vars.bin artifacts/vm-serial.log

    set +e
    host/vm-runner/.build/release/VMRunner artifacts/disk.img artifacts/vm-serial.log \
        --script "$SCRIPT" --script-after "$STATIC_EXIT_LINE" \
        --script-expect "$EXEC_REAP_LINE" --timeout 60 > "$run_log" 2>&1
    local rc=$?
    set -e
    [ -f artifacts/vm-serial.log ] && cp artifacts/vm-serial.log "$serial_copy" || true

    local bytes=0 banner=0 listed=0 loaded=0 hello=0 exited=0 reaped=0 echo_ok=0 fatal=0
    if [ -f artifacts/vm-serial.log ]; then
        bytes="$(wc -c < artifacts/vm-serial.log | tr -d ' ')"
        [ "$(grep -aFxc -- "DipshitOS kernel has seized control." artifacts/vm-serial.log || true)" = 1 ] && banner=1
        [ "$(grep -aFc -- "HELLO.ELF" artifacts/vm-serial.log || true)" -ge 2 ] && listed=1
        [ "$(grep -aFc -- "exec: loaded HELLO.ELF size=" artifacts/vm-serial.log || true)" = 1 ] && loaded=1
        [ "$(grep -aFxc -- "elf: hello from HELLO.ELF" artifacts/vm-serial.log || true)" = 1 ] && hello=1
        [ "$(grep -aFxc -- "$EXEC_EXIT_LINE" artifacts/vm-serial.log || true)" = 1 ] && exited=1
        [ "$(grep -aFxc -- "$EXEC_REAP_LINE" artifacts/vm-serial.log || true)" = 1 ] && reaped=1
        [ "$(grep -aFxc -- "rx-elf-ok" artifacts/vm-serial.log || true)" = 1 ] && echo_ok=1
        grep -qF -- "[EXC] parking:" artifacts/vm-serial.log && fatal=1 || true
    fi
    echo "$tag: runner-rc=$rc serial-bytes=$bytes banner=$banner listed=$listed loaded=$loaded hello=$hello exited=$exited reaped=$reaped echo=$echo_ok fatal=$fatal" | tee -a "$REPORT"
    [ "$rc" = 0 ] && [ "$banner" = 1 ] && [ "$listed" = 1 ] && [ "$loaded" = 1 ] && \
        [ "$hello" = 1 ] && [ "$exited" = 1 ] && [ "$reaped" = 1 ] && \
        [ "$echo_ok" = 1 ] && [ "$fatal" = 0 ]
}

: > "$REPORT"
{
    echo "DIPSHITOS live ELF-loader gate (M22 D1, issue #324, claim 9815)"
    echo "revision: $REVISION branch=$BRANCH boots=$BOOTS dirty-files=$DIRTY"
    echo "script: $(cat "$SCRIPT" | tr '\n' '|')"
    echo "date: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo
} >> "$REPORT"

pass=0
n=0
while [ "$n" -lt "$BOOTS" ]; do
    n=$((n + 1))
    echo
    echo "=== live-elf boot $n ==="
    if run_one "$(printf '%02d' "$n")"; then pass=$((pass + 1)); fi
done

echo
echo "=== result ==="
if [ "$pass" = "$BOOTS" ]; then
    echo "verify-live-elf: PASS — HELLO.ELF parsed by kernel/src/elf.zig through the exec magic-sniff path, mapped at the EL0 text aperture, executed (sys_write marker), and exited cleanly ($pass/$BOOTS boot(s))."
    echo "PASS: $pass/$BOOTS" >> "$REPORT"
    exit 0
fi
echo "verify-live-elf: FAILED — $pass/$BOOTS boot(s) passed; see $REPORT and per-boot logs."
echo "FAIL: $pass/$BOOTS" >> "$REPORT"
exit 1
