//! M73l (#1661) deliverable 2 — cell geometry: THE accessors.
//!
//! Before this card every terminal geometry site said `8` inline
//! (`/ 8`, `* 8`, `fill_rect(..., 8, 8, ...)`) — change the font and
//! every one of them silently disagrees with the painter. After it,
//! terminal geometry is sourced here and nowhere else: cell width is
//! the face's advance at pixel size 13, cell height is ascent +
//! descent (FiraCode Regular, upem 1950, M=W=x 1200 units → exactly
//! 8 × 16). The numbers come from the generated fixture; the pins
//! below fail if a regeneration ever moves them.
//!
//! Chrome/UI text (titles, dock, tooltips, the overview band) keeps
//! font8x8 at literal 8 — it is NOT cell geometry (M73l non-goal).
//! The kernel console's size ladder (text.zig) likewise keeps its own
//! source metrics; only the terminal client area lives here.
//!
//! The atlas itself: kernel/src/font_atlas_data.zig, generated by
//! user/src/lib/font_atlas_gen.zig (regeneration instructions and the
//! byte-compare tripwire live in that file's header/tests).

const std = @import("std");
const data = @import("font_atlas_data.zig");

/// Advance at pixel size 13 — one cell wide.
pub const cell_w: u32 = data.cell_w;
/// Ascent + descent — one cell tall. Visible rows in a client area of
/// `h` pixels are exactly `h / cell_h`.
pub const cell_h: u32 = data.cell_h;
/// A wide (double) cell spans this many pixels.
pub const wide_cell_w: u32 = 2 * cell_w;
/// Baseline offset from the cell top (painters that shear or place
/// descenders by hand read this, not `data`).
pub const ascent: u32 = data.ascent;
pub const descent: u32 = data.descent;
/// The underline stroke sits on the cell's last pixel row.
pub const underline_row: u32 = cell_h - 1;

test "cell metrics pin at the measured values" {
    try std.testing.expectEqual(@as(u32, 8), cell_w);
    try std.testing.expectEqual(@as(u32, 16), cell_h);
    try std.testing.expectEqual(@as(u32, 16), wide_cell_w);
    try std.testing.expectEqual(@as(u32, 12), ascent);
    try std.testing.expectEqual(@as(u32, 4), descent);
    try std.testing.expectEqual(cell_h, ascent + descent);
    try std.testing.expectEqual(cell_h - 1, underline_row);
    // The fixture agrees with this module (one source of truth).
    try std.testing.expectEqual(data.px_size, 13);
    try std.testing.expectEqual(data.cell_w, cell_w);
    try std.testing.expectEqual(data.cell_h, cell_h);
}

fn glyph_bytes(ch: u8) []const u8 {
    const off: usize = (ch - data.first_cp) * data.glyph_bytes;
    return data.blob[off .. off + data.glyph_bytes];
}

test "atlas golden rows — the engine's own bytes, byte-pinned" {
    // The golden_test.go pattern: a handful of glyphs pinned row by row
    // (four 4-bit pixels per byte, high nibble = even x). First observed
    // render, pixel size 13, FiraCode-Regular — cap at rows 3..11 with
    // the baseline at 12, the 'g' descender dropping through rows 12..15.
    const m: [16][4]u8 = .{
        .{ 0x00, 0x00, 0x00, 0x00 }, .{ 0x00, 0x00, 0x00, 0x00 },
        .{ 0x00, 0x00, 0x00, 0x00 }, .{ 0xcf, 0x00, 0x4f, 0x80 },
        .{ 0xcf, 0x40, 0x8c, 0x80 }, .{ 0xcb, 0x80, 0xc8, 0x80 },
        .{ 0xc7, 0xc0, 0xc6, 0x80 }, .{ 0xe1, 0xe3, 0x94, 0xa0 },
        .{ 0xf0, 0xba, 0x54, 0xc0 }, .{ 0xf0, 0x6f, 0x24, 0xc0 },
        .{ 0xf0, 0x28, 0x04, 0xc0 }, .{ 0xf0, 0x00, 0x04, 0xc0 },
        .{ 0x00, 0x00, 0x00, 0x00 }, .{ 0x00, 0x00, 0x00, 0x00 },
        .{ 0x00, 0x00, 0x00, 0x00 }, .{ 0x00, 0x00, 0x00, 0x00 },
    };
    const a: [16][4]u8 = .{
        .{ 0x00, 0x00, 0x00, 0x00 }, .{ 0x00, 0x00, 0x00, 0x00 },
        .{ 0x00, 0x00, 0x00, 0x00 }, .{ 0x00, 0x9f, 0x50, 0x00 },
        .{ 0x00, 0xd8, 0xa0, 0x00 }, .{ 0x02, 0xe2, 0xf0, 0x00 },
        .{ 0x07, 0x90, 0xd5, 0x00 }, .{ 0x0c, 0x40, 0x8a, 0x00 },
        .{ 0x1f, 0x44, 0x7f, 0x00 }, .{ 0x6e, 0xcc, 0xce, 0x50 },
        .{ 0xb6, 0x00, 0x07, 0xa0 }, .{ 0xf1, 0x00, 0x04, 0xf0 },
        .{ 0x00, 0x00, 0x00, 0x00 }, .{ 0x00, 0x00, 0x00, 0x00 },
        .{ 0x00, 0x00, 0x00, 0x00 }, .{ 0x00, 0x00, 0x00, 0x00 },
    };
    const zero: [16][4]u8 = .{
        .{ 0x00, 0x00, 0x00, 0x00 }, .{ 0x00, 0x00, 0x00, 0x00 },
        .{ 0x00, 0x00, 0x00, 0x00 }, .{ 0x2c, 0xde, 0x80, 0x00 },
        .{ 0xb9, 0x05, 0xf4, 0x00 }, .{ 0xf3, 0x0c, 0xca, 0x00 },
        .{ 0xf0, 0x4c, 0x5c, 0x00 }, .{ 0xf0, 0xa4, 0x4c, 0x00 },
        .{ 0xf2, 0xc0, 0x6c, 0x00 }, .{ 0xfc, 0x40, 0x8b, 0x00 },
        .{ 0xdd, 0x00, 0xe6, 0x00 }, .{ 0x4f, 0x9b, 0xc0, 0x00 },
        .{ 0x01, 0x43, 0x00, 0x00 }, .{ 0x00, 0x00, 0x00, 0x00 },
        .{ 0x00, 0x00, 0x00, 0x00 }, .{ 0x00, 0x00, 0x00, 0x00 },
    };
    const g: [16][4]u8 = .{
        .{ 0x00, 0x00, 0x00, 0x00 }, .{ 0x00, 0x00, 0x00, 0x00 },
        .{ 0x00, 0x00, 0x00, 0x00 }, .{ 0x00, 0x00, 0x00, 0x00 },
        .{ 0x00, 0x00, 0x00, 0x00 }, .{ 0x04, 0x88, 0xbf, 0x20 },
        .{ 0x8c, 0x59, 0xe1, 0x00 }, .{ 0xf4, 0x00, 0xd7, 0x00 },
        .{ 0xf5, 0x00, 0xc7, 0x00 }, .{ 0x5e, 0x8b, 0xc1, 0x00 },
        .{ 0x6a, 0x43, 0x00, 0x00 }, .{ 0x7d, 0x88, 0x71, 0x00 },
        .{ 0x04, 0x88, 0xcd, 0x00 }, .{ 0xc0, 0x00, 0x0f, 0x30 },
        .{ 0xea, 0x88, 0xda, 0x00 }, .{ 0x16, 0x87, 0x40, 0x00 },
    };
    inline for (.{ .{ 'M', m }, .{ 'A', a }, .{ '0', zero }, .{ 'g', g } }) |ent| {
        const bytes = glyph_bytes(ent[0]);
        for (ent[1], 0..) |row, y| {
            for (row, 0..) |b, i| {
                try std.testing.expectEqual(b, bytes[y * 4 + i]);
            }
        }
    }
    // Space is the empty cell.
    for (glyph_bytes(' ')) |b| try std.testing.expectEqual(@as(u8, 0), b);
}
